# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
  - repository: qdt-components
    type: github
    endpoint: github.com_demo_team
    name: qlik-demo-team/qdt-components
  - repository: qdt-apps
    type: github
    endpoint: github.com_demo_team
    name: qlikit/qdt-apps
  - repository: qdt-components-ci
    type: git
    name: qdt-components-ci/qdt-components-ci

variables:
  JQ_VERSION: 1.5
  IMAGE: 'ubuntu-latest'

trigger:
- master

pool:
  vmImage: $(IMAGE)

steps:
- checkout: self
  persistCredentials: true
  # clean: true
- checkout: qdt-components
- checkout: qdt-apps
  persistCredentials: true
- checkout: qdt-components-ci

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: $(vmImageName)


        steps:
        - checkout: self
          persistCredentials: true
          # clean: true
        - checkout: qdt-components
        - checkout: qdt-apps
          persistCredentials: true
        - checkout: qdt-components-ci

        - task: NodeTool@0
          inputs:
            versionSpec: '10.x'
          displayName: 'Install Node.js'

        - script: |
            wget --no-check-certificate https://github.com/stedolan/jq/releases/download/jq-$(JQ_VERSION)/jq-linux64 -O /tmp/jq-linux64 && \
            sudo cp /tmp/jq-linux64 /usr/bin/jq && \
            # chmod +x /usr/bin/jq
            sudo chmod +x /usr/bin/jq
          displayName: 'Install JQ'

        - script: |
            mkdir npm
            cd ./qdt-components
            npm install
            npm audit fix
            npm run build
            cd ../
            cp -r ./qdt-components/dist ./npm
            cp ./qdt-components/LICENSE ./npm/LICENSE
            cp ./qdt-components/package.json ./npm/package.json
            cp ./qdt-components/readme.md ./npm/readme.md
          displayName: 'Build qdt-components'

        - script: |
            VER=$(jq -r ".version" < ./qdt-components/package.json)
            mkdir ./qdt-apps/qdt-components/$VER
            git checkout -b ci
            git pull origin master
            cp -r ./qdt-components/dist ./qdt-apps/qdt-components/$VER
            git add .
            git commit -m "qdt-components $VER"
            git push origin ci
          displayName: 'CDN'

        - task: Npm@1
          inputs:
            command: 'publish'
            workingDir: './npm'
            publishEndpoint: 'npmjs.com_demo_team'
          displayName: 'Npm publish'
